sonar.organization=norahbiju
sonar.projectKey=Norahbiju_hospital-management-system

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.