name: DevSecOps Pipeline

run-name: Build-Scan-Push

on:
  push:
    branches: [ "deploying" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hospital-actions
      TAG: v1.1.1

    steps:
    # 🔹 Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 🔹 Setup Java (Required for Maven + SonarQube)
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 🔹 Build Project (IMPORTANT for SonarQube)
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # 🔹 SonarQube Scan (SAST)
    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=hospital-management-system \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # 🔹 Install Snyk
    - name: Install Snyk
      run: npm install -g snyk

    # 🔹 Authenticate Snyk
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # 🔹 Snyk SCA Scan (Dependencies)
    - name: Snyk SCA Scan
      run: snyk test || true

    # 🔹 Setup Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # 🔹 Build Docker Image
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:$TAG .

    # 🔹 Snyk Container Scan
    - name: Snyk Container Scan
      run: snyk container test $IMAGE_NAME:$TAG || true

    # 🔹 Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y trivy

    # 🔹 Trivy Image Scan
    - name: Scan Docker Image with Trivy
      run: |
        trivy image --severity HIGH,CRITICAL --exit-code 0 $IMAGE_NAME:$TAG

    # 🔹 Login to DockerHub
    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 🔹 Tag Docker Image
    - name: Tag Docker Image
      run: docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

    # 🔹 Push Docker Image
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
